general:
  cfApiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
  cfOrg: '0ceb0976trial'
  cfSpace: 'dev'
  cfCredentialsId: 'CF_Mohit'
  cfServiceInstance: 'atc_system'
  cfServiceKeyName: 'ABAP_SAP_COM_0510'
stages:
  Prepare System:
    cfService: 'abap'
    cfServicePlan: 'standard'
    abapSystemAdminEmail: 'mohit.q.sharma@accenture.com'
    abapSystemDescription: 'ABAP Environment Q System'
    abapSystemIsDevelopmentAllowed: false
    abapSystemID: 'H02'
    abapSystemSizeOfPersistence: 4
    abapSystemSizeOfRuntime: 1
    cfServiceKeyConfig: 'serviceKey.json'
  Clone Repositories:
    repositories: 'repositories.yml'
    strategy: 'Clone'
  ATC:
    atcConfig: 'atcConfig.yml'
  Post:
    confirmDeletion: true
steps:
  cloudFoundryDeleteService:
    cfDeleteServiceKeys: true
